import { AccountProposal } from "@prisma/client"
import { Account } from "app/account/types"
import { ProposalApproval } from "app/proposalApproval/types"
import { Check } from "@prisma/client"
import { Rfp } from "app/rfp/types"

export enum ProposalStatus {
  SUBMITTED = "SUBMITTED",
  IN_REVIEW = "IN_REVIEW",
  APPROVED = "APPROVED",
}

export type ProposalMetadata = {
  content: {
    title: string
    body: string
  }
  funding: {
    recipientAddress: string
    token: string
    symbol: string
    amount: string
  }
  signature: string
}

// for some reason, prisma autogenerated is not picking up account
type AccountProposalExtended = AccountProposal & {
  account?: Account
}

export type Proposal = {
  id: string
  status: ProposalStatus
  data: ProposalMetadata
  createdAt: Date
  collaborators: AccountProposalExtended[]
  approvals: ProposalApproval[]
  checks: Check[]
  rfp?: Rfp
}
