import { ZodToken } from "app/types/zod"
import * as z from "zod"

// convenience metadata for application consumption, metadata is verifiable on-chain
// taking typescript type generated by zod for type alignment
export type Token = z.infer<typeof ZodToken>
