// need wallet address to mint nft
// nft number will call the respective smart contract
export const users = {
  "0x65A3870F48B5237f27f674Ec42eA1E017E111D63": {
    fname: "michael",
    handle: "0xmcg",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["frontend, backend, nft"],
    terminals: ["station"],
    initiatives: ["web"],
    nftId: 1,
  },
  "0xd32FA3e71737a19eE4CA44334b9f3c52665a6CDB": {
    fname: "mind",
    handle: "mindapi",
    role: "staff",
    address: "",
    pronouns: "she/her",
    skills: ["design", "product"],
    terminals: ["station", "poolsuite"],
    initiatives: ["brand", "web"],
    nftId: 2,
  },
  "0x78918036a8e4B9179bEE3CAB57110A3397986E44": {
    fname: "tina",
    handle: "fakepixels",
    role: "staff",
    address: "",
    pronouns: "she/her",
    skills: ["entrepreneurship", "investing", "design"],
    terminals: ["station", "juicebox", "seedclub"],
    initiatives: ["newstand", "terminal partnership"],
    nftId: 3,
  },
  "0x17B7163E708A06De4DdA746266277470dd42C53f": {
    fname: "brendan",
    handle: "brendo",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["design"],
    terminals: ["station"],
    initiatives: ["protocol"],
    nftId: 4,
  },
  "0x6Cf61c97674C65c68D1E816eCCf36061aCD9a65c": {
    fname: "darian",
    handle: "WGMIApe",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["subgraph"],
    terminals: ["station"],
    initiatives: ["protocol"],
    nftId: 5,
  },
  "0xB0F0bA31aA582726E36Dc0c79708E9e072455eD2": {
    fname: "calvin",
    handle: "cchengasaurus",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["tokenomics"],
    terminals: ["station"],
    initiatives: ["protocol"],
    nftId: 6,
  },
  "0xaE55f61f85935BBB68b8809d5c02142e4CbA9a13": {
    fname: "kristen",
    handle: "rie",
    role: "commuter",
    address: "",
    pronouns: "she/her",
    skills: ["frontend"],
    terminals: ["station"],
    initiatives: ["web"],
    nftId: 7,
  },
  "0x016562aA41A8697720ce0943F003141f5dEAe006": {
    fname: "conner",
    handle: "symmtry",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["architect", "mathematician"],
    terminals: ["station"],
    initiatives: ["protocol"],
    nftId: 0,
  },
  "0x5716e900249D6c35afA41343a2394C32C1B4E6cB": {
    fname: "kash",
    handle: "honeykashmoney",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["chakra", "blitz", "tailwind"],
    terminals: ["station"],
    initiatives: ["protocol"],
    nftId: 8,
  },
  "0x8FAA5498Ca6fc9A61BA967E07fBc9420aab99E55": {
    fname: "akshay",
    handle: "wagmiking",
    role: "commuter",
    address: "",
    pronouns: "he/him",
    skills: ["subgraphs"],
    terminals: ["station"],
    initiatives: ["protocol"],
    nftId: 9,
  },
}

export const terminals = {
  station: {
    terminalName: "Station",
    handle: "station",
    staff: ["mindapi", "fakepixels", "cswenberg"],
    commuter: ["brendo"],
    visitor: ["rie"],
    initiatives: ["protocol", "brand", "web", "terminal partnership"],
  },
  poolsuite: {
    terminalName: "Poolsuite",
    handle: "poolsuite",
    staff: [],
    commuter: [],
    visitor: ["mindapi"],
    initiatives: [],
  },
  juicebox: {
    terminalName: "Juicebox",
    handle: "juicebox",
    staff: [],
    commuter: ["fakepixels"],
    visitor: [],
    initiatives: [],
  },
  seedclub: {
    terminalName: "Seedclub",
    handle: "seedclub",
    staff: ["fakepixels"],
    commuter: [],
    visitor: ["fakepixels"],
    initiatives: [],
  },
}
